import Head from "next/head";
import Image from "next/image";
import Style from "@/styles/Home.module.css";
import { Container, Row, Col, Button } from "react-bootstrap";

export default function Home() {
  return (
    <>
      <Head>
        <title>NR HOSTEL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${Style.home} pt-5`}>
        <Container>
          <div className="headerTitle">
            <h3 class="headerTitleMain">Book Your Seat</h3>
          </div>
          <Row>
            <Col md={3} sm={12}>
              <div
                style={{ border: "1px solid gray", borderRadius: "5px" }}
                className="mb-4"
              >
                <img src="/fh.jpg" className="img-fluid w-full" alt="" />
                <span
                  className="text-center text-white d-flex justify-content-center align-items-center"
                  style={{ background: "gray", padding: "3px 12px" }}
                >
                  Available seat: 05
                </span>
                <hr />
                <div className="p-2">
                  <h4 style={{ fontSize: "20px", fontWeight: 700 }}>
                    ভূতের বাড়ি
                  </h4>
                  <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
                  <div className="d-flex justify-content-center align-items-center mt-2">
                    <Button className="py-1 px-3">বিস্তারিত</Button>
                  </div>
                </div>
              </div>
            </Col>
            <Col md={3} sm={12}>
              <div
                style={{ border: "1px solid gray", borderRadius: "5px" }}
                className="mb-4"
              >
                <img src="/fh.jpg" className="img-fluid w-full" alt="" />
                <span
                  className="text-center text-white d-flex justify-content-center align-items-center"
                  style={{ background: "gray", padding: "3px 12px" }}
                >
                  Available seat: 05
                </span>
                <hr />
                <div className="p-2">
                  <h4 style={{ fontSize: "20px", fontWeight: 700 }}>
                    ভূতের বাড়ি
                  </h4>
                  <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
                  <div className="d-flex justify-content-center align-items-center mt-2">
                    <Button className="py-1 px-3">বিস্তারিত</Button>
                  </div>
                </div>
              </div>
            </Col>
            <Col md={3} sm={12}>
              <div
                style={{ border: "1px solid gray", borderRadius: "5px" }}
                className="mb-4"
              >
                <img src="/fh.jpg" className="img-fluid w-full" alt="" />
                <span
                  className="text-center text-white d-flex justify-content-center align-items-center"
                  style={{ background: "gray", padding: "3px 12px" }}
                >
                  Available seat: 05
                </span>
                <hr />
                <div className="p-2">
                  <h4 style={{ fontSize: "20px", fontWeight: 700 }}>
                    ভূতের বাড়ি
                  </h4>
                  <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
                  <div className="d-flex justify-content-center align-items-center mt-2">
                    <Button className="py-1 px-3">বিস্তারিত</Button>
                  </div>
                </div>
              </div>
            </Col>
            <Col md={3} sm={12}>
              <div
                style={{ border: "1px solid gray", borderRadius: "5px" }}
                className="mb-4"
              >
                <img src="/fh.jpg" className="img-fluid w-full" alt="" />
                <span
                  className="text-center text-white d-flex justify-content-center align-items-center"
                  style={{ background: "gray", padding: "3px 12px" }}
                >
                  Available seat: 05
                </span>
                <hr />
                <div className="p-2">
                  <h4 style={{ fontSize: "20px", fontWeight: 700 }}>
                    ভূতের বাড়ি
                  </h4>
                  <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
                  <div className="d-flex justify-content-center align-items-center mt-2">
                    <Button className="py-1 px-3">বিস্তারিত</Button>
                  </div>
                </div>
              </div>
            </Col>
            <Col md={3} sm={12}>
              <div
                style={{ border: "1px solid gray", borderRadius: "5px" }}
                className="mb-4"
              >
                <img src="/fh.jpg" className="img-fluid w-full" alt="" />
                <span
                  className="text-center text-white d-flex justify-content-center align-items-center"
                  style={{ background: "gray", padding: "3px 12px" }}
                >
                  Available seat: 05
                </span>
                <hr />
                <div className="p-2">
                  <h4 style={{ fontSize: "20px", fontWeight: 700 }}>
                    ভূতের বাড়ি
                  </h4>
                  <h5 style={{ fontSize: "18px" }}>২/৩ ফার্মগেট, ঢাকা</h5>
                  <div className="d-flex justify-content-center align-items-center mt-2">
                    <Button className="py-1 px-3">বিস্তারিত</Button>
                  </div>
                </div>
              </div>
            </Col>
          </Row>
        </Container>
      </main>
    </>
  );
}
